### PR TITLE
[NEW APP] Golem Network Provider

### PR DESCRIPTION
**Pull request by cryptobench**
Hello! I have added some configs and images for a Golem Network provider. 

The Golem Networks allows one to rent out their idle hardware resources and earn GLM tokens for the work they've computed for the requestors on the network. 

It's basically a decentralized cloud like AWS where you can rent out resources, but instead it runs on normal computers like yours and mine.

### CODE REVIEW

**Comment by meienberger** [comment]
Looks good to me, I'll just need to update the logo to make it a 512x512px jpg before merging

**Comment by cryptobench** [comment]
Thank you @meienberger . I have gone ahead and resized the image to 512x512.

**Comment by meienberger** [comment]
I have an issue when I try to run it on my server:
Screenshot 2022-09-24 at 15 29 39

**Comment by cryptobench** [comment]
> I have an issue when I try to run it on my server: Screenshot 2022-09-24 at 15 29 39

Are you using an ARM processor?

**Comment by meienberger** [comment]
Yes I am using an ARM64 processor

**Comment by cryptobench** [comment]
Okay, that's the issue then. Running a golem provider is only possible on x86-64. I have an M1 macbook too, but I did the testing on my Intel desktop pc because of that limitation.

**Comment by meienberger** [comment]
Okay, I will develop a feature to hide incompatible apps before merging this PR

**Comment by cryptobench** [comment]
Sounds good. Thank you very much.

**Comment by meienberger** [comment]
The feature will soon be implemented https://github.com/meienberger/runtipi/pull/244

**Comment by steveiliop56** [comment]
Closing since the project is not maintained anymore.

**Comment by cryptobench** [comment]
> Closing since the project is not maintained anymore.

Which project? Tipi or Golem?

**Comment by steveiliop56** [comment]
The specific golem docker image lmao not tipi.

**Comment by meienberger** [comment]
Sorry @cryptobench I forgot about this PR... Are you still maintaining the image? We can re-open and make it work

**Pull request closed without merging**
