### PR TITLE
Add sudo password

### PR DESCRIPTION
**Pull request by rollingafull**
This password permit install packages on debian container for improve functionalities, like git, ansible, and others.

## Summary by CodeRabbit

- **New Features**
	- Added a new configuration field for "Sudo Password" with constraints on length and type.
	- Added the `SUDO_PASSWORD` environment variable to the `code-server` service configuration.

### CODE REVIEW

**Comment by meienberger** [comment]
Shouldn't we add it to the docker-compose.yml aswell? Have you tested it?

**Comment by rollingafull** [comment]
I'm sorry, i couldn't try it.
There is another pull request for docker-compose.yml.

**Comment by meienberger** [comment]
> I'm sorry, i couldn't try it.
> 
> There is another pull request for docker-compose.yml.

Is it possible to do one PR for both? Or point the other one to this one

**Comment by rollingafull** [comment]
Added docker-compose.yml to PR.

**Comment by steveiliop56** [comment]
Well... closing that since it is a duplicate of this https://github.com/runtipi/runtipi-appstore/pull/2936

**Pull request closed without merging**
