### PR TITLE
refactor(olivetin): use latest image

### PR DESCRIPTION
**Pull request by steveiliop56**

### CODE REVIEW

**Comment by JigSawFr** [comment]
@steveiliop56 Latest ? Since when ? We avoid this tag

**Comment by steveiliop56** [comment]
Don't worry. I chatted with the developer a bit, he uses calver and renovate doesn't. He isn't doing breaking updates that's why I chose to use latest.

**Comment by JigSawFr** [comment]
@steveiliop56 Just that users needs to know they need to restart the app to update when a new tag version is published. As tipi version will never change

**Comment by steveiliop56** [comment]
Yeah indeed but it's better than the app not getting any updates : )

**Pull request merged**
