### PR TITLE
App/electrs

### PR DESCRIPTION
**Pull request by MontejoJorge**
## Summary by CodeRabbit

- **New Features**
  - Added configuration for `electrs-ui` and `electrs` services to the application, enhancing deployment flexibility and network settings.
  - Included Traefik routing rules for secure HTTPS and local domain access.

- **Documentation**
  - Updated documentation to provide comprehensive information about Electrs, including setup guidance, synchronization warnings, required apps, and a screenshot of the Electrs UI.

### CODE REVIEW

**Comment by DireMunchkin** [comment]
Hello @MontejoJorge , thanks for contributing Electrs! I was trying to run this with the bitcoind in Tipi, but it doesn't seem to have generated a `.cookie` file. Without it Electrs won't start. Could you clarify how you're supposed to get a `.cookie` file? I was trying to google this but didn't get much help.

**Comment by MontejoJorge** [comment]
@DireMunchkin 

> When no -rpcpassword is specified, the daemon now uses a special ‘cookie’ file for authentication. This file is generated with random content when the daemon starts, and deleted when it exits. Its contents are used as authentication token. Read access to this file controls who can access through RPC. By default it is stored in the data directory but its location can be overridden with the option -rpccookiefile.

Electrs does not allow to pass custom rpc username and password using enviroment variables but a custom config file, i should adapt this to allow it on tipi.

**Comment by DireMunchkin** [comment]
Aha, now I understood the problem after your explanation - It was that the `-server` flag in `bitcoind` in Tipi is default off. The option is labeled "Accept JSON-RPC" in the UI.

This is kind of unintuitive or undocumented - I'd suggest either adding to the tooltip in electrs a hint that RPC needs to be on, or to turn on RPC by default in bitcoind. I didn't understand that RPC has something to do with a local file being generated.

Switching to RPC username / password config in electrs would also have worked, then I'd have understood that RPC being on was necessary.

**Comment by DireMunchkin** [comment]
I still have a problem connecting to the Tipi Bitcoin instance - I'm attaching the logs below:
```
Max lines:

electrs-ui  |
electrs-ui  | > electrs-ui@0.9.2 dev:backend /app
electrs-ui  | > pnpm --filter backend run start
electrs-ui  |
electrs     | Starting electrs 0.10.2 on x86_64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", db_log_dir: None, daemon_dir: "/root/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 172.19.0.7:8332, daemon_p2p_addr: 172.19.0.7:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.10.2 (Electrum Rust Server)!", signet_magic: f9beb4d9, args: [] }
electrs     | [2024-06-10T18:59:40.390Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
electrs     | [2024-06-10T18:59:40.390Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
electrs     | [2024-06-10T18:59:40.404Z INFO  electrs::db] "/data/db/bitcoin": 311 SST files, 0.000316576 GB, 0.000000021 Grows
electrs     | [2024-06-10T18:59:40.405Z INFO  electrs::db] closing DB at /data/db/bitcoin
electrs     | Error: electrs failed
electrs     |
electrs     | Caused by:
electrs     |     0: bitcoind RPC polling failed
electrs     |     1: daemon not available
electrs     |     2: JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 111)
```
I left the Bitcoin node option as default blank - This doesn't work for me. Could you look into how `bitcoind` and `electrs` connect so that it will just work "out of the box"? It's nice that it's fully configurable and all, but for a project like Tipi the main aim is to have default settings that work together.

Usually with services on Tipi I use the internal IP and the port number to connect - I tried this as well and it just gives you a "connection reset by peer" instead. Is it possible there's still some missing setting in Bitcoin or Electrs that'd make this work better?

**Comment by MontejoJorge** [comment]
@DireMunchkin thanks for your feedback, fixed in #3732

**Comment by DireMunchkin** [comment]
@meienberger Hey, thanks for merging this, but I didn't get Electrs to work in Tipi myself (see https://github.com/runtipi/runtipi-appstore/pull/3336#issuecomment-2159167500), did you test it works?

**Comment by MontejoJorge** [comment]
> @meienberger Hey, thanks for merging this, but I didn't get Electrs to work in Tipi myself (see [#3336 (comment)](https://github.com/runtipi/runtipi-appstore/pull/3336#issuecomment-2159167500)), did you test it works?

You have to update the bitcoin app, or enable the `Accept JSON-RPC requests` option in config

**Comment by DireMunchkin** [comment]
No, that's a separate issue, I still have that problem after enabling RPC

**Comment by MontejoJorge** [comment]
My bad @DireMunchkin, I was testing it against my custom btc daemon setup and didnt realize that I had a few settings at the end of the config file, (hopefully) fixed in #3768. This time I tried it in a new setup, and it seems like it's working.
image

**Pull request merged**
