### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by austinsr1**
Fixed from upstream discussion. https://github.com/FlowiseAI/Flowise/pull/2563

## Summary by CodeRabbit

- **Chore**
  - Updated the startup command configuration for the `flowise` service in the `docker-compose.yml` file for better alignment with best practices.

### CODE REVIEW

**Comment by JigSawFr** [comment]
@austinsr1 can you bump the tipi version in config.json also please ?

**Comment by JigSawFr** [comment]
@austinsr1 I mean the tipi_version field of config.json file :)

**Comment by austinsr1** [comment]
Thanks for the feedback. Im not all familiar with github and i ended up adding a separate pr for it somehow.

**Comment by JigSawFr** [comment]
@austinsr1 No problem thanks for your contribution !

**Pull request closed without merging**
