### PR TITLE
[NEW APP] Pterodactyl Panel

### PR DESCRIPTION
**Pull request by meienberger**

### CODE REVIEW

**Comment by DrMxrcy** [comment]
Any updates on getting Pterodactyl in here?

**Comment by DrMxrcy** [comment]
https://github.com/EdyTheCow/docker-pterodactyl
https://bitbucket.org/Gethec/pterodactyl-wings/src/master/

**Comment by steveiliop56** [comment]
@meienberger any updates?

**Comment by arvalaan** [comment]
Would love to get this in here, given there are already docker-compose installations available, I would imagine we could simply reference the work of EdyTheCow right?

**Comment by steveiliop56** [comment]
Hello @arvalaan will finish it soon.

**Comment by meienberger** [comment]
At the time I tried to make this work (almost 2 years ago) I was unsuccessful because the app requires you to enter the container and run commands inside to set it up. Maybe this has changed as of today

**Comment by meienberger** [comment]
Closing as it is largely outdated

**Pull request closed without merging**
