### PR TITLE
[NEW APP] Jellystat

### PR DESCRIPTION
**Pull request by JamsRepos**
Adds Jellystat to the App Store.

### CODE REVIEW

**Comment by meienberger** [comment]
Hello @JamsRepos thanks for submitting the app! While I was testing it I discovered something very odd. The app seems to be running in development mode and is compiling the code on the fly. This needs to be brought up to the developer as it causes performance slowdown. Also I get a database error when first running the app

```
> jfstat@1.0.8 start-app
> concurrently "npm run start-server" "npm start"

[0]
[0] > jfstat@1.0.8 start-server
[0] > cd backend && node server.js
[0]
[1]
[1] > jfstat@1.0.8 start
[1] > react-scripts start
[1]
[0] error: database "tipi" does not exist
[0]     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
[0]     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
[0]     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
[0]     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
[0]     at Socket.emit (node:events:514:28)
[0]     at addChunk (node:internal/streams/readable:376:12)
[0]     at readableAddChunk (node:internal/streams/readable:349:9)
[0]     at Readable.push (node:internal/streams/readable:286:10)
[0]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[0] FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[0] FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[0] Server listening on http://127.0.0.1:3003
[0] Activity Interval: 1000
[1] Browserslist: caniuse-lite is outdated. Please run:
[1]   npx update-browserslist-db@latest
[1]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
[1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
[1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
[1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
[1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
[1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
[1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
[1] Proxy middleware applied
[1] (node:94) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[1] (Use `node --trace-deprecation ...` to show where the warning was created)
[1] (node:94) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[1] Starting the development server...
[1]
[1] Compiled with warnings.
[1]
[1] [eslint]
[1] src/pages/components/item-info.js
[1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]
[1] Search for the keywords to learn more about each warning.
[1] To ignore, add // eslint-disable-next-line to the line before.
[1]
[1] WARNING in [eslint]
[1] src/pages/components/item-info.js
[1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]
[1] webpack compiled with 1 warning
[1] Compiling...
[1] Compiled with warnings.
[1]
[1] [eslint]
[1] src/pages/components/item-info.js
[1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]
[1] Search for the keywords to learn more about each warning.
[1] To ignore, add // eslint-disable-next-line to the line before.
[1]
[1] WARNING in [eslint]
[1] src/pages/components/item-info.js
[1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]
[1] webpack compiled with 1 warning
```

**Comment by JamsRepos** [comment]
> Hello @JamsRepos thanks for submitting the app! While I was testing it I discovered something very odd. The app seems to be running in development mode and is compiling the code on the fly. This needs to be brought up to the developer as it causes performance slowdown. Also I get a database error when first running the app
> 
> ```
> > jfstat@1.0.8 start-app
> > concurrently "npm run start-server" "npm start"
> 
> [0]
> [0] > jfstat@1.0.8 start-server
> [0] > cd backend && node server.js
> [0]
> [1]
> [1] > jfstat@1.0.8 start
> [1] > react-scripts start
> [1]
> [0] error: database "tipi" does not exist
> [0]     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
> [0]     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
> [0]     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
> [0]     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
> [0]     at Socket.emit (node:events:514:28)
> [0]     at addChunk (node:internal/streams/readable:376:12)
> [0]     at readableAddChunk (node:internal/streams/readable:349:9)
> [0]     at Readable.push (node:internal/streams/readable:286:10)
> [0]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
> [0] FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
> [0] FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
> [0] Server listening on http://127.0.0.1:3003
> [0] Activity Interval: 1000
> [1] Browserslist: caniuse-lite is outdated. Please run:
> [1]   npx update-browserslist-db@latest
> [1]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
> [1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
> [1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
> [1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
> [1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
> [1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
> [1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
> [1] [HPM] Proxy created: /  -> http://127.0.0.1:3003
> [1] Proxy middleware applied
> [1] (node:94) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
> [1] (Use `node --trace-deprecation ...` to show where the warning was created)
> [1] (node:94) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
> [1] Starting the development server...
> [1]
> [1] Compiled with warnings.
> [1]
> [1] [eslint]
> [1] src/pages/components/item-info.js
> [1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
> [1]
> [1] Search for the keywords to learn more about each warning.
> [1] To ignore, add // eslint-disable-next-line to the line before.
> [1]
> [1] WARNING in [eslint]
> [1] src/pages/components/item-info.js
> [1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
> [1]
> [1] webpack compiled with 1 warning
> [1] Compiling...
> [1] Compiled with warnings.
> [1]
> [1] [eslint]
> [1] src/pages/components/item-info.js
> [1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
> [1]
> [1] Search for the keywords to learn more about each warning.
> [1] To ignore, add // eslint-disable-next-line to the line before.
> [1]
> [1] WARNING in [eslint]
> [1] src/pages/components/item-info.js
> [1]   Line 105:4:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
> [1]
> [1] webpack compiled with 1 warning
> ```

I've sent this PR to the developer, hoping he can shed some insight, not sure about the database error - but we'll overcome that once this main issue is resolved.

**Comment by meienberger** [comment]
Any news on this one? @JamsRepos

**Comment by JamsRepos** [comment]
> Any news on this one? @JamsRepos 

Chasing them now, seems it was missed.

**Comment by steveiliop56** [comment]
@JamsRepos @meienberger closing this for inactivity.

**Pull request closed without merging**
