### PR TITLE
automatisch

### PR DESCRIPTION
**Pull request by hsnpai**
my hetzner

## Summary by CodeRabbit

- **Chores**
  - Updated configuration details for the "Automatisch App" to improve clarity and setup.
  - Upgraded `docker-compose.yml` to version '3.9' with enhanced service configurations for better performance and reliability.

### CODE REVIEW

**Comment by meienberger** [comment]
What is this @hsnpai?

**Review by meienberger — CHANGES_REQUESTED** [review]
Do not merge

**Comment by hsnpai** [comment]
Hi Nicolas,

Thank you for your feedback on my pull request. I apologize that I wasn't aware it would be reviewed. As a beginner, I'm still learning the ropes, and I appreciate your guidance.

I'll be sure to carefully consider your comments and make the necessary revisions.

Thanks again,

**Comment by steveiliop56** [comment]
Hello @hsnpai,

In order to add the app to the runtipi app store you need to follow these instructions https://runtipi.io/docs/contributing/adding-a-new-app  It shouldn't take you long to add it and the docs are very clear and easy to go through. 

(By the way sorry for being a bit too harsh, Nicolas thought this was an accidental pull request)

**Pull request closed without merging**
