### PR TITLE
Make domain configurable

### PR DESCRIPTION
**Pull request by DireMunchkin**
Fixes https://github.com/runtipi/runtipi-appstore/issues/4462

## Summary by CodeRabbit

- **New Features**
	- Updated the version number to enhance application functionality.
	- Introduced a new configuration option for users to specify their local domain name, improving configurability.

- **Bug Fixes**
	- Modified environment variable from `${APP_DOMAIN}` to `${INVIDIOUS_DOMAIN}` in multiple configuration files to ensure consistent domain resolution and flexibility in port configuration.

### CODE REVIEW

**Comment by DireMunchkin** [comment]
Some quick testing on how the domain variable behaves:

- Setting it to invidious.tipi.lan will fix the original issue
- Leaving it blank is also valid and will allow connection from several domains

**Comment by DireMunchkin** [comment]
I also incorporated feedback from @iBicha to set a default on the port.

**Comment by DireMunchkin** [comment]
@meienberger @rollingafull You've also been active on this config, do you have thoughts on this way to solve the problem?

**Comment by rollingafull** [comment]
Hello, it's a very good solution. For the port i would leave it as you suggest, but for the domain i would create a new optional variable with the name of the external domain if you want to use it and if it is empty, let invidious be installed with the default values.
I did it this way initially but after a suggestion from @meienberger, I initialized it with APP_DOMAIN, which caused this problem in the default installation.

How do you see it @DireMunchkin and @meienberger ?

**Comment by rollingafull** [comment]
Can see this [pr](https://github.com/runtipi/runtipi-appstore/pull/3714/files/1fd65bd2ace3d6cb6c12790898135ac0ef065d72#diff-a75fe47fac749fd824396f9bdb0966ac6fa8e12dac1e8229aee97751d17c58d5) as example.

`    {
      "type": "text",
      "label": "Domain",
      "hint": "Your local domain name for you instance",
      "placeholder": "example.com",
      "required": false,
      "env_variable": "INVIDIOUS_DOMAIN"
     }`

`        hmac_key: ${INVIDIOUS_HMAC_KEY}
        use_innertube_for_captions: true
        domain: ${INVIDIOUS_DOMAIN}
        external_port: ${INVIDIOUS_EXTERNAL_PORT}
        https_only: ${INVIDIOUS_HTTPS_ONLY}`

**Comment by DireMunchkin** [comment]
@rollingafull I think what you propose is more or less what I did in the PR? Could you clarify what the difference is?

**Comment by rollingafull** [comment]
Yes, I hadn't looked closely sorry.
Everything seems correct to me as it is.

Thank you.

**Comment by meienberger** [comment]
Thank you @DireMunchkin

**Pull request merged**
