### PR TITLE
[Home Assistant] Change to host mode

### PR DESCRIPTION
**Pull request by MontejoJorge**
> `network_mode: host` must be used to put Home Assistant on the host’s network, **otherwise certain functionality - including mDNS and UPnP - will break**. The -p command line option or the compose file equivalent ports: is not compatible with host networking mode and must not be used.

https://www.home-assistant.io/installation/alternative#docker-compose

## Summary by CodeRabbit

- **New Features**
  - Updated `config.json` to support the latest version (19) of the `homeassistant-1` app.

- **Refactor**
  - Changed network configuration in `homeassistant-1` to use `network_mode: host` for improved performance.
  - Adjusted volume mappings for better data organization.

### CODE REVIEW

**Comment by JigSawFr** [comment]
@MontejoJorge Hello, sorry but don't agree to use host mode here. If you need to use Multicast DNS, add the MDNS app in the store, it will works ;) this is how I'm doing atm.

**Comment by MontejoJorge** [comment]
> @MontejoJorge Hello, sorry but don't agree to use host mode here. If you need to use Multicast DNS, add the MDNS app in the store, it will works ;) this is how I'm doing atm.

@JigSawFr in my case, i cant add the Apple HomeKit Bridge

**Comment by JigSawFr** [comment]
> > @MontejoJorge Hello, sorry but don't agree to use host mode here. If you need to use Multicast DNS, add the MDNS app in the store, it will works ;) this is how I'm doing atm.
> 
> 
> 
> @JigSawFr in my case, i cant add the Apple HomeKit Bridge

This is exactly what I'm doing to have the HomeKit bridge, but you also need to set the advertise IP in HA. I've added links to MDNS/HA description on store.

**Comment by JigSawFr** [comment]
So for all that you Homekit bridge support in this HA app.
Install and configure MDNS app from the Tipi store.
Edit config of HA app to reflect this part: https://www.home-assistant.io/integrations/homekit#docker-network-isolation

**Pull request closed without merging**
