### PR TITLE
Update Peppermint

### PR DESCRIPTION
**Pull request by DrMxrcy**

### CODE REVIEW

**Comment by DrMxrcy** [comment]
Tested and working on my end!

**Comment by steveiliop56** [comment]
Will test too!

**Comment by steveiliop56** [comment]
@DrMxrcy it worked on my machine too, I would only recommend to change the logo. They seem to have updated it.

**Review by meienberger — APPROVED** [review]

**Comment by meienberger** [comment]
Doesn't the exposed domain work in this case? Instead of adding a new var

**Review by steveiliop56 — APPROVED** [review]

**Pull request merged**
