### PR TITLE
feat(app): add recyclarr

### PR DESCRIPTION
**Pull request by JigSawFr**
Hi there !
Please find bellow a new app.

### Recyclarr
_Automatically sync TRaSH Guides to your Sonarr and Radarr instances_

## Information's
- [x] No GUI / CLI mode enabled
- [x] Not port used
- [x] Available but not Exposable
- [x] Use default value for optional vars
- [x] Heavily tested !

Done 💯

### CODE REVIEW

**Comment by JigSawFr** [comment]
@meienberger if you can do your magic for the logo 👯

**Comment by steveiliop56** [comment]
Well @JigSawFr here you go:
new_logo

**Comment by meienberger** [comment]
How does it connect to my arrs? I've to admit I don't understand this app completely

**Comment by JigSawFr** [comment]
@meienberger it's mainly CLI based, so you need to add yml config files, with url/api key to connect and configure. But at the end you will end up with a nice quality of your fetched files.

**Comment by JigSawFr** [comment]
> Well @JigSawFr here you go:
> 
> new_logo
> 
> 

Thanks

**Pull request merged**
