### PR TITLE
Fix lodestone-core not saving data in ${APP_DATA_DIR}/data/lodestone-data

### PR DESCRIPTION
**Pull request by damnkrat**
For some reason, lodestone-core works with root account instead of "user" account. So the volume from his account is useless, but there may be data stored there. This pull request merges the user folder and the root account thereby fixing the error

### CODE REVIEW

**Comment by DrMxrcy** [comment]
Can you bump the ```"tipi_version"``` in the config.json?

**Comment by damnkrat** [comment]
Shure

**Comment by damnkrat** [comment]
@DrMxrcy Could you merge?

**Comment by steveiliop56** [comment]
Hello @damnkrat ,

The docs [here](https://github.com/Lodestone-Team/lodestone_core) use ```/home/user/.lodestone```.

**Comment by damnkrat** [comment]
@steveiliop56 Yes, but for some reason, the container uses the root account and the folder ends up in the wrong place. I have to manually reassign it in portainer to access the instance files. You can try it yourself if you wish

**Comment by steveiliop56** [comment]
Alright,

Before I merge can you remove these lines: ```    user: ${TIPI_UID}:${TIPI_GID} 
    group_add: 
    - ${TIPI_GID}```?

**Comment by steveiliop56** [comment]
Alright seems to work fine merging...

**Pull request merged**
